import Logo from "@/components/Logo";
import Table from "@/components/Table";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coinease</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <Logo />
        <Table />
      </main>
    </>
  );
}
